#!/bin/sh
#Start a gdb session with the (local) openocd target -- 3/2/20 brent@mbari.org
#  first run make unless GDBstart env var is defined
: ${PROJECT:=`basename $PWD`}
: ${BINARY:=$PROJECT.elf}
[ -r $BINARY ] || BINARY=build/$BINARY
[ $GDBstart ] || make || exit $?
: ${GDBstart:=~/stm32l-discovery/start.gdb}
: ${GDB:=/cortex/bin/gdb}

echo "==>  \`tail -f openocd.log\` to monitor target debug log  <=="
exec $GDB -x $GDBstart "$@" $BINARY
